---

- name: create groups for users
  group:
    name: '{{ item.username }}'
    gid: '{{ item.uid }}'
  with_items: capistrano_setup_users
  when: capistrano_setup_users is defined


- name: create users
  user:
    name: '{{ item.username }}'
    group: '{{ item.username }}'
    groups: '{{ item.groups|join(",") }}'
    shell: '{{ item.shell }}'
    comment: '{{ item.name }}'
    uid: '{{ item.uid }}'
    home: '{{ item.home }}'
    createhome: '{{ item.createhomedir }}'
    password: '{{ item.password }}'
    update_password: '{{ item.update_password }}'
  with_items: capistrano_setup_users
  when: capistrano_setup_users is defined


- name: create .ssh directory
  file:
    path: '~{{ item.username }}/.ssh'
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 0750
  with_items: capistrano_setup_users
  when: capistrano_setup_users is defined and item.createhomedir and item.upload_key

- name: upload ssh keys
  copy:
    src: '{{ item.pub_key }}'
    dest: '~{{ item.username }}/.ssh/authorized_keys'
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 0640
  with_items: capistrano_setup_users
  when: capistrano_setup_users is defined and item.createhomedir and item.upload_key

